### ISSUE TITLE
Set Up Web Hosting

### ISSUE THREAD

**Issue by wyattshanahan** [ClaireG-J/IntroSE_03#36]
Web hosting needs to be configured and set up. Currently, the hosting url will be wls219.pythonanywhere.com

**Comment by wyattshanahan** [comment]
Site is live hosted. I'll get image files for all of the products uploaded soon

**Comment by wyattshanahan** [comment]
Image files added to the remote host. Finalised debugging is needed

**Comment by ClaireG-J** [comment]
closed for the end of sprint 3
